### ISSUE TITLE
ffmpeg exited with code 1: Error opening filters!

### ISSUE THREAD

**Issue by Starfight** [markokajzer/discord-soundbot#108]
I have this bot on my server that I update regularly. But with latest update, when I try to add a sound with a discord command on a Youtube video, I have this error in logs:

```
Error: ffmpeg exited with code 1: Error opening filters!
     at ChildProcess.<anonymous> (/srv/discord-soundbot/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
     at ChildProcess.emit (events.js:315:20)
     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
```

I have install ffmpeg via apt:

```
$ ffmpeg -version
ffmpeg version 3.2.15-0+deb9u2 Copyright (c) 2000-2020 the FFmpeg developers
built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
configuration: --prefix=/usr --extra-version=0+deb9u2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libebur128 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
libavutil      55. 34.101 / 55. 34.101
libavcodec     57. 64.101 / 57. 64.101
libavformat    57. 56.101 / 57. 56.101
libavdevice    57.  1.100 / 57.  1.100
libavfilter     6. 65.100 /  6. 65.100
libavresample   3.  1.  0 /  3.  1.  0
libswscale      4.  2.100 /  4.  2.100
libswresample   2.  3.100 /  2.  3.100
libpostproc    54.  1.100 / 54.  1.100
```

Thanks for your work.

**Comment by markokajzer** [comment]
I believe your ffmpeg version is a bit outdated.

```
$ ffmpeg -version
ffmpeg version 4.2.4-1ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers
```

Can you try upgrading with `sudo apt-get update ffmpeg`?

Let me know if that works.

**Comment by Starfight** [comment]
I try to update directly from ffmpeg website because I have debian 9 on my server.
Now I have:

```
Error: ffmpeg exited with code 1: Error reinitializing filters!
Failed to inject frame into filter network: Invalid argument
Error while processing the decoded data for stream #0:1
Conversion failed!
    at ChildProcess.<anonymous> (/srv/discord-soundbot/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
```

with

```
$ ffmpeg -version
ffmpeg version 4.3.1-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2020 the FFmpeg developers
```

**Comment by markokajzer** [comment]
What's the video you are using? I tried with this [bruh ](https://www.youtube.com/watch?v=2ZIpFytCSVc)sound effect, and everything works fine as far as I can tell. Can you try with that? Let me know which one you are using.

**Comment by Starfight** [comment]
I try to add a sound with this command:
```
!add gagner https://www.youtube.com/watch?v=IVTlem1zVmU 00:10 00:03
```

Maybe it's just a problem with this video.

**Comment by markokajzer** [comment]
Oh... it looks like you were trying to specify the duration of the clip in that last parameter. It is not the duration anymore, but the end time of the clip.

Try

```
!add gagner https://www.youtube.com/watch?v=IVTlem1zVmU 00:10 00:13
```

**Comment by markokajzer** [comment]
I guess I made a breaking change in a minor version bump, but you can always read up on the changes of a version, [here](https://github.com/markokajzer/discord-soundbot/blob/master/CHANGELOG.md#210-2020-11-21).

**Comment by Starfight** [comment]
Ok thank you! Sorry I forgot to read changes before and the error log didn't have much to do with the problem.
Thank you for your time.
