### ISSUE TITLE
how can i install ffmpeg?

### ISSUE THREAD

**Issue by RedFame01** [markokajzer/discord-soundbot#22]
Hi. thanks for create the bot, it works. but I can't play any sound, when I use the command "! sound", in my cmd I got this error 
"Error occured!
Error: FFMPEG not found
    at Function.selectFfmpegCommand (C:\discord-soundbot-master\node_modules\prism-media\src\transcoders\ffmpeg\Ffmpeg.js:46:13)
    at new FfmpegTranscoder (C:\discord-soundbot-master\node_modules\prism-media\src\transcoders\ffmpeg\Ffmpeg.js:7:37)
    at new MediaTranscoder (C:\discord-soundbot-master\node_modules\prism-media\src\transcoders\MediaTranscoder.js:10:19)
    at new Prism (C:\discord-soundbot-master\node_modules\prism-media\src\Prism.js:5:23)
    at VoiceConnection (C:\discord-soundbot-master\node_modules\discord.js\src\client\voice\VoiceConnection.js:46:18)
    at Promise (C:\discord-soundbot-master\node_modules\discord.js\src\client\voice\ClientVoiceManager.js:63:22)
    at ClientVoiceManager.joinChannel (C:\discord-soundbot-master\node_modules\discord.js\src\client\voice\ClientVoiceManager.js:45:12)
    at VoiceChannel.join (C:\discord-soundbot-master\node_modules\discord.js\src\structures\VoiceChannel.js:120:30)
    at SoundBot.playSoundQueue (C:\discord-soundbot-master\src\SoundBot.js:114:18)
    at SoundBot.handleSoundCommands (C:\discord-soundbot-master\src\SoundBot.js:95:47)"

I use this guide to install ffmpeg https://goo.gl/Xc2CcG

**Comment by markokajzer** [comment]
Well, the error says it all: `FFMPEG not found`. So, there is a problem with your installation. What happens when you type `ffmpeg -version` into the console, like in the last step of the tutorial?

**Comment by RedFame01** [comment]
Thanks for rapid answer! If I run `ffmpeg -version` I get this 
"ffmpeg version N-90173-gfa0c9d69d3 Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 7.3.0 (GCC)
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libmfx --enable-amf --enable-cuda --enable-cuvid --enable-d3d11va --enable-nvenc --enable-dxva2 --enable-avisynth
libavutil      56.  7.101 / 56.  7.101
libavcodec     58. 13.100 / 58. 13.100
libavformat    58. 10.100 / 58. 10.100
libavdevice    58.  2.100 / 58.  2.100
libavfilter     7. 12.100 /  7. 12.100
libswscale      5.  0.101 /  5.  0.101
libswresample   3.  0.101 /  3.  0.101
libpostproc    55.  0.100 / 55.  0.100"

I run rhis command `npm install ffmpeg-binaries` in the bot folder, and now if I play a sound the bot come in my channel , but it don't say anything and now I got this error:
"Error: OPUS_ENGINE_MISSING
    at Object.exports.fetch.engineOptions [as fetch] (C:\discord-soundbot-master\node_modules\discord.js\src\client\voice\opus\OpusEngineList.js:27:9)
    at AudioPlayer.playUnknownStream (C:\discord-soundbot-master\node_modules\discord.js\src\client\voice\player\AudioPlayer.js:96:37)
    at VoiceConnection.playFile (C:\discord-soundbot-master\node_modules\discord.js\src\client\voice\VoiceConnection.js:453:24)
    at voiceChannel.join.then (C:\discord-soundbot-master\src\SoundBot.js:115:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
"

**Comment by markokajzer** [comment]
How about running `npm install`?

**Comment by RedFame01** [comment]
it's the same, here you can find the log of `npm install` 
http://www.mediafire.com/file/hnl028kqlsnu965/2018-03-03T17_18_45_023Z-debug.log

**Comment by markokajzer** [comment]
Of course, it's the same, since there was an error with the installation. It says: `231 error Failed at the node-opus@0.2.7 install script.`, `230 error node-opus@0.2.7 install: node-gyp rebuild`, `211 verbose optional Failed using git.`. Seems like you don't have `git` installed? How did you download this project, per zip file?

Again, it seems like you are a beginner, so maybe using Docker would be the better solution. Please install the dependencies **CORRECTLY**, and at least try to read the terminal output a little bit.

**Comment by RedFame01** [comment]
Now the bos is working great! :)
I install opus by run this command `npm install discord.js opusscript` and now the bot reproduces the sounds. Thank you so much, this is the only one soundbot that works great :)

**Comment by markokajzer** [comment]
Glad, it works. If you have any recommendations, feel free tell me about it.

**Comment by markokajzer** [comment]
Let me just add that `opusscript` is not the recommended library. If you find any issues, try `node-opus` instead. See [this link](https://github.com/discordjs/discord.js#audio-engines) for reference.

**Comment by powerflips** [comment]
How did you solve it? I have the same problem.

**Comment by markokajzer** [comment]
Just a couple of comments above your question [he answered it](https://github.com/markokajzer/discord-soundbot/issues/22#issuecomment-370178154). However, as I already said, using `opusscript` is not recommended.

If you have problems with installation after following the detailed guide in the [wiki](https://github.com/markokajzer/discord-soundbot/wiki/Installation), feel free to open a new issue, or join the Discord and talk to me directly.

**Comment by TTV-igifoxes** [comment]
А мне вот выше перечисленное, не помогло решить проблему с (Error: FFMPEG not found)

**Comment by Lunas-Adlaw** [comment]
This is the problem that I get, I already unistall and install ffmpeg again, it dosen't work.
please help.

(node:14852) UnhandledPromiseRejectionWarning: Error: FFmpeg/avconv not found!
    at Function.getInfo (C:\Users\Yukiis\Desktop\Bot Lupha\node_modules\prism-media\src\core\FFmpeg.js:130:11)
    at Function.create (C:\Users\Yukiis\Desktop\Bot Lupha\node_modules\prism-media\src\core\FFmpeg.js:143:38)
    at new FFmpeg (C:\Users\Yukiis\Desktop\Bot Lupha\node_modules\prism-media\src\core\FFmpeg.js:44:27)
    at AudioPlayer.playUnknown (C:\Users\Yukiis\Desktop\Bot Lupha\node_modules\discord.js\src\client\voice\player\BasePlayer.js:47:20)
    at VoiceConnection.play (C:\Users\Yukiis\Desktop\Bot Lupha\node_modules\discord.js\src\client\voice\util\PlayInterface.js:71:28)    at play (C:\Users\Yukiis\Desktop\Bot Lupha\index.js:109:40)
    at C:\Users\Yukiis\Desktop\Bot Lupha\index.js:143:9
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:14852) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on
unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:14852) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by markokajzer** [comment]
It seems like you are on Windows so you should download FFMPEG, and put it directly into the folder of the bot, which seems to be `C:\Users\Yukiis\Desktop\Bot Lupha` in your case.

For a detailed guide and more information, you can [follow the guide here](https://github.com/markokajzer/discord-soundbot/wiki/Windows). The installation of FFMPEG is described starting from step 5.

The author of this issue also described his solution, [clicky here](https://github.com/markokajzer/discord-soundbot/issues/22#issuecomment-370178154).

If that STILL does not work, you can try to install ffmpeg via npm (see [here](https://www.npmjs.com/package/ffmpeg-static)). To do this, simply type in `yarn add ffmpeg-static`.
