### ISSUE TITLE
Incorrect login

### ISSUE THREAD

**Issue by Guisch** [markokajzer/discord-soundbot#28]
Hey,

I always get this error when launching the bot
Note that the config.json file is filled in correctly
```
> dicord-soundbot@1.0.1 start /home/guisch/discord-soundbot
> npm run build && npm run serve


> dicord-soundbot@1.0.1 build /home/guisch/discord-soundbot
> tsc -p tsconfig.json


> dicord-soundbot@1.0.1 serve /home/guisch/discord-soundbot
> node dist/bot.js

Use the following URL to let the bot join your server!
https://discordapp.com/oauth2/authorize?client_id=XXX&scope=bot
(node:23218) UnhandledPromiseRejectionWarning: Error: Incorrect login details were provided.
    at WebSocketConnection.client.ws.connection.once.event (/home/guisch/discord-soundbot/node_modules/discord.js/src/client/ClientManager.js:47:41)
    at Object.onceWrapper (events.js:272:13)
    at WebSocketConnection.emit (events.js:180:13)
    at WebSocketConnection.onClose (/home/guisch/discord-soundbot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:390:10)
    at WebSocketClient.internalOnClose (/home/guisch/discord-soundbot/node_modules/uws/uws.js:121:17)
    at process.nextTick (/home/guisch/discord-soundbot/node_modules/uws/uws.js:64:19)
    at process._tickCallback (internal/process/next_tick.js:112:11)
(node:23218) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:23218) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by markokajzer** [comment]
Well, it says:

```
Error: Incorrect login details were provided.
```

Please double and triple check your login data. Make sure you copy the following two fields correctly.

<img width="716" alt="bildschirmfoto 2018-03-27 um 23 44 41" src="https://user-images.githubusercontent.com/9379317/37996934-aecc03ba-3219-11e8-9756-8a820ca06d12.png">

<img width="719" alt="bildschirmfoto 2018-03-27 um 23 45 57" src="https://user-images.githubusercontent.com/9379317/37996914-9f30c684-3219-11e8-9d96-af78527ebaeb.png">

And just to make sure... Does it really say `client_id=XXX` in the link or did you obfuscate it for this issue?

**Comment by Guisch** [comment]
Yes I do Obfuscate it.
I Just put "Client Secret" instead of "Token" sorry. Thanks !

**Comment by markokajzer** [comment]
Hope everything else works and you like it. Cheers!
