### ISSUE TITLE
Error: Could not locate the bindings file.

### ISSUE THREAD

**Issue by stroopwafel1337** [markokajzer/discord-soundbot#32]
Everything went fine, but when I try to play a sound, it only end up doing this.

Error occured!
 { Error: Could not locate the bindings file. Tried:
 → C:\Users\varadi\Desktop\discord-soundbot-1.0.2\node_modules\node-opus\build\node-opus.node
 → C:\Users\varadi\Desktop\discord-soundbot-1.0.2\node_modules\node-opus\build\Debug\node-opus.node
 → C:\Users\varadi\Desktop\discord-soundbot-1.0.2\node_modules\node-opus\build\Release\node-opus.node
 → C:\Users\varadi\Desktop\discord-soundbot-1.0.2\node_modules\node-opus\out\Debug\node-opus.node
 → C:\Users\varadi\Desktop\discord-soundbot-1.0.2\node_modules\node-opus\Debug\node-opus.node
 → C:\Users\varadi\Desktop\discord-soundbot-1.0.2\node_modules\node-opus\out\Release\node-opus.node
 → C:\Users\varadi\Desktop\discord-soundbot-1.0.2\node_modules\node-opus\Release\node-opus.node
 → C:\Users\varadi\Desktop\discord-soundbot-1.0.2\node_modules\node-opus\build\default\node-opus.node
 → C:\Users\varadi\Desktop\discord-soundbot-1.0.2\node_modules\node-opus\compiled\8.11.4\win32\x64\node-opus.node
    at bindings (C:\Users\varadi\Desktop\discord-soundbot-1.0.2\node_modules\bindings\bindings.js:88:9)
    at Object.<anonymous> (C:\Users\varadi\Desktop\discord-soundbot-1.0.2\node_modules\node-opus\lib\OpusEncoder.js:4:34)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\varadi\Desktop\discord-soundbot-1.0.2\node_modules\node-opus\index.js:4:19)
  tries:
   [ 'C:\\Users\\varadi\\Desktop\\discord-soundbot-1.0.2\\node_modules\\node-opus\\build\\node-opus.node',
     'C:\\Users\\varadi\\Desktop\\discord-soundbot-1.0.2\\node_modules\\node-opus\\build\\Debug\\node-opus.node',
     'C:\\Users\\varadi\\Desktop\\discord-soundbot-1.0.2\\node_modules\\node-opus\\build\\Release\\node-opus.node',
     'C:\\Users\\varadi\\Desktop\\discord-soundbot-1.0.2\\node_modules\\node-opus\\out\\Debug\\node-opus.node',
     'C:\\Users\\varadi\\Desktop\\discord-soundbot-1.0.2\\node_modules\\node-opus\\Debug\\node-opus.node',
     'C:\\Users\\varadi\\Desktop\\discord-soundbot-1.0.2\\node_modules\\node-opus\\out\\Release\\node-opus.node',
     'C:\\Users\\varadi\\Desktop\\discord-soundbot-1.0.2\\node_modules\\node-opus\\Release\\node-opus.node',
     'C:\\Users\\varadi\\Desktop\\discord-soundbot-1.0.2\\node_modules\\node-opus\\build\\default\\node-opus.node',
     'C:\\Users\\varadi\\Desktop\\discord-soundbot-1.0.2\\node_modules\\node-opus\\compiled\\8.11.4\\win32\\x64\\node-opus.node' ] }

Can you guys help me?

**Comment by markokajzer** [comment]
Hm... never had that error. Let's start with your node and npm. Can you tell me the output of `node --version` and `npm --version`?

**Comment by stroopwafel1337** [comment]
Node version is v8.11.4
npm version is 5.6.0

Yes I have installed everything according.

**Comment by markokajzer** [comment]
Closed since we solved the issue on Discord! 🙂
