### ISSUE TITLE
ffmpeg issue.

### ISSUE THREAD

**Issue by mahmedov** [markokajzer/discord-soundbot#5]
Any idea why? I installed ffmpeg and yet it is still not playing any sounds.

```DevOS:discord-soundbot dev$ npm start

> dicord_soundbot@0.7.0 start /Users/dev/Desktop/discord-soundbot
> node bot.js

Use the following URL to let the bot join your server!
https://discordapp.com/oauth2/authorize?client_id=293861510478954497&scope=bot
Error occured!
Error: FFMPEG not found
    at Function.selectFfmpegCommand (/Users/dev/Desktop/discord-soundbot/node_modules/prism-media/src/transcoders/ffmpeg/Ffmpeg.js:46:13)
    at new FfmpegTranscoder (/Users/dev/Desktop/discord-soundbot/node_modules/prism-media/src/transcoders/ffmpeg/Ffmpeg.js:7:37)
    at new MediaTranscoder (/Users/dev/Desktop/discord-soundbot/node_modules/prism-media/src/transcoders/MediaTranscoder.js:10:19)
    at new Prism (/Users/dev/Desktop/discord-soundbot/node_modules/prism-media/src/Prism.js:5:23)
    at VoiceConnection (/Users/dev/Desktop/discord-soundbot/node_modules/discord.js/src/client/voice/VoiceConnection.js:45:18)
    at Promise (/Users/dev/Desktop/discord-soundbot/node_modules/discord.js/src/client/voice/ClientVoiceManager.js:63:22)
    at ClientVoiceManager.joinChannel (/Users/dev/Desktop/discord-soundbot/node_modules/discord.js/src/client/voice/ClientVoiceManager.js:45:12)
    at VoiceChannel.join (/Users/dev/Desktop/discord-soundbot/node_modules/discord.js/src/structures/VoiceChannel.js:114:30)
    at SoundBot.playSoundQueue (/Users/dev/Desktop/discord-soundbot/src/SoundBot.js:40:18)
    at MessageHandler.handle (/Users/dev/Desktop/discord-soundbot/src/MessageHandler.js:39:74)```

**Comment by markokajzer** [comment]
Issue fixed?

**Comment by mahmedov** [comment]
yeah!

**Comment by asazs** [comment]
how you fix this?

**Comment by markokajzer** [comment]
Make sure FFMPEG is installed and in the PATH. Don't forget to restart your Terminal.

**Comment by mahmedov** [comment]
Everything worked after I followed the steps thoroughly, I messed up on PATHing

**Comment by Fransisco4492** [comment]
hey what are the steps?

**Comment by markokajzer** [comment]
Here is a detailed installation guide: https://github.com/markokajzer/discord-soundbot/wiki/Windows.

If you still have any problems, join the Discord and I will help you there!
