### ISSUE TITLE
Bot stops reacting after a while

### ISSUE THREAD

**Issue by Jufoli** [markokajzer/discord-soundbot#56]
Hey! First of all thanks for the work with this Sound Bot!
I got mine running on a cloud machine and at first everything seems to be ok. After a while the bot leaves (I turned on the config that he should stay in a channel) and never comes back. 
I still see him as online user, so the proccess should still be running in the cloud.
When I checked the logs I saw this error message:
```
Error occured!
 TypeError: Cannot read property 'join' of undefined
    at SoundQueue.playNext (/home/ubuntu/discord-soundbot/dist/src/queue/SoundQueue.js:66:14)
    at SoundQueue.onFinishedPlayingSound (/home/ubuntu/discord-soundbot/dist/src/queue/SoundQueue.js:98:18)
    at currentSound.channel.join.then.then.then.connection (/home/ubuntu/discord-soundbot/dist/src/queue/SoundQueue.js:69:38)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:20011) UnhandledPromiseRejectionWarning: DiscordAPIError: Unknown Message
    at item.request.gen.end (/home/ubuntu/discord-soundbot/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
    at then (/home/ubuntu/discord-soundbot/node_modules/snekfetch/src/index.js:215:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:20011) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 9)
(node:20011) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Any Idea who I could fix it?

Greetings,
Jufoli!

**Comment by markokajzer** [comment]
Hey, thanks for reaching out! Looks like there is an error on my side. Any hints on what you did to trigger this error? May it be related to entrance / exist sounds?

The `DiscordAPIError: Unknown Message` error seems like you have `deleteMessages` enabled, but already deleted the message manually. Could that be right?

**Comment by z1g** [comment]
For the first part of Jufoli's error:

`Error occured!
 TypeError: Cannot read property 'join' of undefined
    at SoundQueue.playNext (/home/ubuntu/discord-soundbot/dist/src/queue/SoundQueue.js:66:14)
    at SoundQueue.onFinishedPlayingSound (/home/ubuntu/discord-soundbot/dist/src/queue/SoundQueue.js:98:18)
    at currentSound.channel.join.then.then.then.connection (/home/ubuntu/discord-soundbot/dist/src/queue/SoundQueue.js:69:38)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

I get the same error when a user has an exit sound enabled.  Once that error occurs the bot will stay connected but no longer play any request sounds or entrance sounds. `

**Comment by Jufoli** [comment]
@markokajzer Well I can't really reproduce it yet. I also guess it was related to the entrance sounds but since I placed them inside the db.json file I don't have any problems anymore.
As soon as I can reproduce it and know what could possible trigger it, I'll let you know.

Thanks!

**Comment by markokajzer** [comment]
Heyy 👋 There was definitely a bug with exit sounds. I think it should be fixed now, could you pull the latest `master` changes and try again?

I don't use `!entrance` and `!exit` myself to be honest, so I guess I should have tested them a bit better :D Thanks to all of you for the info and the bug report!
